"""initial schema: users, farms, memberships, financial records, documents, category budgets, loans, onboarding

Revision ID: d072751a8543
Revises: 
Create Date: 2026-08-17 13:02:16.781781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd072751a8543'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('dataset_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_slug'), 'farms', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_dev_placeholder', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category_budgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('annual_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allocation_rule', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("record_type IN ('income', 'expense')", name='ck_category_budget_record_type'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'sector', 'record_type', 'category', 'year', 'month', name='uq_category_budget_slot')
    )
    op.create_index(op.f('ix_category_budgets_farm_id'), 'category_budgets', ['farm_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counterparty', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('attachment_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('linked_financial_record_id', sa.String(length=32), nullable=True),
    sa.Column('possible_duplicate_manual_record_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('invoice', 'receipt')", name='ck_document_type'),
    sa.CheckConstraint("payment_status IN ('unpaid', 'paid')", name='ck_document_payment_status'),
    sa.CheckConstraint("record_type IN ('income', 'expense')", name='ck_document_record_type'),
    sa.CheckConstraint("review_status IN ('confirmed', 'pending_review', 'rejected')", name='ck_document_review_status'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'source', 'provider_reference', name='uq_document_provider_reference')
    )
    op.create_index(op.f('ix_documents_farm_id'), 'documents', ['farm_id'], unique=False)
    op.create_table('farm_memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'manager', 'advisor', 'accountant', 'read_only')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'farm_id', name='uq_membership_user_farm')
    )
    op.create_table('financial_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('counterparty', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('origin_document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("record_type IN ('income', 'expense')", name='ck_financial_record_type'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_document_id', name='uq_financial_record_origin_document')
    )
    op.create_index(op.f('ix_financial_records_farm_id'), 'financial_records', ['farm_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_repayment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('maturity', sa.String(length=7), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_farm_id'), 'loans', ['farm_id'], unique=False)
    op.create_table('onboarding_profiles',
    sa.Column('farm_id', sa.String(length=32), nullable=False),
    sa.Column('farm_type', sa.String(length=20), nullable=True),
    sa.Column('current_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('loans', sa.JSON(), nullable=False),
    sa.Column('loan_repayments_annual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('farm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_profiles')
    op.drop_index(op.f('ix_loans_farm_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_financial_records_farm_id'), table_name='financial_records')
    op.drop_table('financial_records')
    op.drop_table('farm_memberships')
    op.drop_index(op.f('ix_documents_farm_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_category_budgets_farm_id'), table_name='category_budgets')
    op.drop_table('category_budgets')
    op.drop_table('users')
    op.drop_index(op.f('ix_farms_slug'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
